//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventario.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Equipo()
        {
            this.SalidaEquipoes = new HashSet<SalidaEquipo>();
        }
    
        public int Id { get; set; }
        public int EmpleadoId { get; set; }
        public int MarcaId { get; set; }
        public string Procesador { get; set; }
        public string Memoria { get; set; }
        public string Disco { get; set; }
        public int AsignacionId { get; set; }
        public string Serial { get; set; }
        public int ModeloId { get; set; }
        public int MonitorId { get; set; }
        public int AccesorioId { get; set; }
        public Nullable<System.DateTime> Fcreacion { get; set; }
        public Nullable<System.DateTime> Factualizacion { get; set; }
        public Nullable<System.DateTime> Fdespacho { get; set; }
    
        public virtual Accesorio Accesorio { get; set; }
        public virtual Asignacion Asignacion { get; set; }
        public virtual Empleado Empleado { get; set; }
        public virtual Marca Marca { get; set; }
        public virtual Modelo Modelo { get; set; }
        public virtual Monitor Monitor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalidaEquipo> SalidaEquipoes { get; set; }
    }
}
