//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventario.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LoginExAndresEntities : DbContext
    {
        public LoginExAndresEntities()
            : base("name=LoginExAndresEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<modulo> moduloes { get; set; }
        public virtual DbSet<Rol> Rols { get; set; }
        public virtual DbSet<RolAdmin> RolAdmins { get; set; }
        public virtual DbSet<RolConsulta> RolConsultas { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<usuario> usuarios { get; set; }
        public virtual DbSet<Accesorio> Accesorios { get; set; }
        public virtual DbSet<Asignacion> Asignacions { get; set; }
        public virtual DbSet<Empleado> Empleadoes { get; set; }
        public virtual DbSet<Marca> Marcas { get; set; }
        public virtual DbSet<Modelo> Modeloes { get; set; }
        public virtual DbSet<Monitor> Monitors { get; set; }
        public virtual DbSet<Equipo> Equipoes { get; set; }
        public virtual DbSet<SalidaEquipo> SalidaEquipoes { get; set; }
    }
}
